### ISSUE TITLE
Error Comp Plot Coherence

### ISSUE THREAD

**Issue by jennyrogenz** [JesseRed/dataVis#10]
Hallo Carsten,
ich habe die neue Version aus dem main-Ordner heruntergeladen. Bei show data kann ich mir die Coherence nicht mehr anzeigen lassen und es erscheint die Fehlermeldung "Error in upperTriangle: konnte Funktion "upperTriangle" nicht finden". 

![error upper triangle](https://user-images.githubusercontent.com/78802531/107525031-b633cc80-6bb6-11eb-9985-49b9b70d1dcf.png)

Liebe Grüße
Jenny

**Comment by JesseRed** [comment]
solved
