### ISSUE TITLE
Error Image save

### ISSUE THREAD

**Issue by jennyrogenz** [JesseRed/dataVis#12]
Hallo Carsten,
ich wollte gern den Circle Plot als png-Datei speichern. Das hat leider nicht funktioniert und die App stürzt dabei ab. Es erschien folgender Fehler:
Error in grid.newpage: could not open file 'outputimages/ImageOutput_hist2021-02-11-16-22-42.png

Als ich die p-heatmap speichern wollte, erschien die Fehlermeldung aus dem Anhang.
![error imagesave](https://user-images.githubusercontent.com/78802531/107659231-388bc180-6c87-11eb-8263-b476c8df1400.png)

Liebe Grüße
Jenny

**Comment by JesseRed** [comment]
solved
daten werden nun im Verzeichnis mit den Daten gespeichert
