### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by stebro01** [JesseRed/dataVis#19]
export geht nicht: 

Fehlermeldung: cannot open compressed file './exported_variables_from_visualizer/ExportData2D_mat_p.Rds', probable reason 'No such file or directory'
Warning: Error in gzfile: cannot open the connection

**Comment by stebro01** [comment]
auf quito / Biomag

**Comment by JesseRed** [comment]
wird nun im Verzeichnis von wo die Daten eingeladen werden gespeichert
