### ISSUE TITLE
import fMRT Data

### ISSUE THREAD

**Issue by stebro01** [JesseRed/dataVis#23]
bitte f. Import von fmri_corr >> auch fmri_syn und fmri_trans zulassen >>> Funktionen / Felder sind identisch, es bit nur eine Fehlermeldung,d as der Typ nicht erkannt wird; wenn ich das im JSON per Hand auf fmri_corr ändere, geht alles automatisch

**Comment by JesseRed** [comment]
da stellt sich die Frage wie wir es organisieren wollen

- Siehst du irgend einen unterschied in deiner Datenstruktur zwischen MEG  Coherence  und MRT correlation ? bis auf die Tatsache, das es nur eine Frequenz gibt?

- wie hast du fmri_syn berechnet? unterscheidet es sich in der Datenstruktur von Correlation?

- Transferentropy ist ja wieder gerichtet ...

- unterscheidet sich das irgendwie von MEG transferentropy oder von fMRI Granger?

ich sollte das eher methodisch zusammenfassen

**Comment by JesseRed** [comment]
solved
