### ISSUE TITLE
Zuordnung Means Barchart

### ISSUE THREAD

**Issue by LauraOp** [JesseRed/dataVis#26]
Hallo Carsten, 
aus der Barchart die unterhalb des Corrplots angezeigt wird kann man nicht entnehmen, welcher Mean zu welchem Trial gehört wenn man 2 Trials innerhalb einer Gruppe vergleicht (siehe Screenshot). 
Zu welchem Trial gehört der erste der beiden means im grauen Kasten unten rechts?
Danke!
LG Laura
![BarChart_TrialComparison](https://user-images.githubusercontent.com/78084719/110784372-e7f98b00-8269-11eb-9aee-3a2f06176d50.png)

**Comment by JesseRed** [comment]
Liebe Laura,

das ist ein bug
hab ich in der neuen Version behoben ... aber da gibt es so viele
Veraenderungen
muessen mal schauen wie wir da den uebergang machen

bg


Am Do., 11. März 2021 um 13:02 Uhr schrieb LauraOp ***@***.***

**Comment by JesseRed** [comment]
solved
