### ISSUE TITLE
TE: unterste Zeile Corrplot funktioniert nicht

### ISSUE THREAD

**Issue by LauraOp** [JesseRed/dataVis#38]
Bei TE funktioniert die unterste Zeile des Corrplots nicht, korrigierte p-Werte werden nicht angezeigt
![corrplot](https://user-images.githubusercontent.com/78084719/112729140-f5ca3400-8f2a-11eb-8bb4-63ffca4f5263.png)

**Comment by JesseRed** [comment]
solved
