### ISSUE TITLE
corrplot

### ISSUE THREAD

**Issue by LauraOp** [JesseRed/dataVis#4]
corrplot wird nicht angezeigt

**Comment by JesseRed** [comment]
was fuer ein bloeder fehler .... geht jetzt wieder mit der neuen Version ...
nutzt auch unbedingt die Optionen links fuer die Anzeige von nummern und significanzen
![image](https://user-images.githubusercontent.com/17439688/106066993-0d896580-60fe-11eb-9ab6-0ea1980371a1.png)

**Comment by LauraOp** [comment]
Alles klar, vielen Dank!

Gesendet von Mail für Windows 10

Von: JesseRed
Gesendet: Donnerstag, 28. Januar 2021 00:17
An: JesseRed/dataVis
Cc: LauraOp; Author
Betreff: Re: [JesseRed/dataVis] corrplot (#4)

was fuer ein bloeder fehler .... geht jetzt wieder mit der neuen Version ...
nutzt auch unbedingt die Optionen links fuer die Anzeige von nummern und significanzen
