### ISSUE TITLE
Datenplausibilität prüfen

### ISSUE THREAD

**Issue by LauraOp** [JesseRed/dataVis#49]
Vergleich 2 Trials, 2 Gruppen, 1 Zeitpunkt, Regionenunterschied

**Comment by JesseRed** [comment]
fuer mich sieht hier alles sehr gut und plausibel aus, testdatensaetze laufen ohne Probleme,
wenn irgend etwas unplausibles auftritt dann bitte mit Datensatz und bild von der Stelle bitte nochmal an mich
