### ISSUE TITLE
TE preprocessing

### ISSUE THREAD

**Issue by LauraOp** [JesseRed/dataVis#5]
Preprocessing für Transferentropie stürzt ab
Error in get_methodname: unknown datatype detected with type=conn_trans

**Comment by JesseRed** [comment]
ich hab gar kein aktuelles transfer entropy datafile kannst du mir mal
bitte eins schicken?

Am Do., 28. Jan. 2021 um 16:33 Uhr schrieb LauraOp <notifications@github.com

**Comment by LauraOp** [comment]
Hallo Carsten,
die zwei Files sind im Anhang.
Viele Grüße
Laura

Gesendet von Mail für Windows 10

Von: JesseRed
Gesendet: Donnerstag, 28. Januar 2021 20:22
An: JesseRed/dataVis
Cc: LauraOp; Author
Betreff: Re: [JesseRed/dataVis] TE preprocessing (#5)

ich hab gar kein aktuelles transfer entropy datafile kannst du mir mal
bitte eins schicken?

Am Do., 28. Jan. 2021 um 16:33 Uhr schrieb LauraOp <notifications@github.com

**Comment by JesseRed** [comment]
Transferentropy ist nun einladbar und auch ein merging der daten 
die funktionen sind in den main branch inkludiert
