### ISSUE TITLE
Regions order

### ISSUE THREAD

**Issue by jennyrogenz** [JesseRed/dataVis#8]
Hallo Carsten,
mir ist aufgefallen, dass bei Umordnung der region order in der Coherence sich auch die p-heatmap und die circle map ändert. Es werden dann andere Regionen zueinander signifikant, obwohl die Einstellungen gleich sind.  Muss ich bei der Umordnung etwas bestimmtes beachten?
Viele Grüße
Jenny
![0-3Hz(2)](https://user-images.githubusercontent.com/78802531/107372119-5de0ca00-6ae5-11eb-957d-cd7b03d7ab37.png)
![0-3Hz](https://user-images.githubusercontent.com/78802531/107372123-5e796080-6ae5-11eb-99b0-25fac2f39705.png)

**Comment by JesseRed** [comment]
ein bug der die t-werte nicht richtig kopiert hat ... das faellt primaer beim Circle auf da der die t-Werte verwendet 
bug war seit dem letzten grossen update vor ca. 2 wochen rein gekommen
